services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - NEXT_PUBLIC_CLOUD_FLARE_ACCESS_KEY_ID=${NEXT_PUBLIC_CLOUD_FLARE_ACCESS_KEY_ID}
      - NEXT_PUBLIC_CLOUD_FLARE_SECRET_ACCESS_KEY=${NEXT_PUBLIC_CLOUD_FLARE_SECRET_ACCESS_KEY}
      - NEXT_PUBLIC_CLOUD_FLARE_BUCKET_NAME=${NEXT_PUBLIC_CLOUD_FLARE_BUCKET_NAME}
      - NEXT_PUBLIC_CLOUD_FLARE_REGION=${NEXT_PUBLIC_CLOUD_FLARE_REGION}
      - NEXT_PUBLIC_CLOUD_FLARE_ENDPOINT=${NEXT_PUBLIC_CLOUD_FLARE_ENDPOINT}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    restart: always
